line-length = 80

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "FBT", # flake8-boolean-trap
    "B",   # flake8-bugbear
    "I",   # isort
    "UP",  # pyupgrade
    "C4",  # flake8-comprehensions
    "Q",   # flake8-quotes
    "RUF", # ruff-specific rules
    "PL",  # pylint
]

ignore = [
    "F401",     # unused imports (иногда нужно для __all__)
    "PLR0913",  # too many arguments
]

[lint.isort]
known-first-party = ["page_analyzer"]
